contentTypes: [json, yaml]
logLevel: info
schemaBasePath: ./jsonschema/
shouldDereference: false
shouldSymlinkExtensionless: true
shouldSymlinkLatest: false
ignoreSchemas:
  - /toolinfo/1.0.0
  - /toolinfo/1.1.1
