pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: built-python
        build: dev-python

      - name: lint-python
        build: lint-python

      - name: test-python
        build: test-python
        run:
          env:
            DJANGO_SECRET_KEY: NOTAREALSECRET
            DB_ENGINE: django.db.backends.sqlite3
            DB_NAME: ":memory:"
            WIKIMEDIA_OAUTH2_KEY: NOTAREALOAUTHKEY
            WIKIMEDIA_OAUTH2_SECRET: NOTAREALOAUTHSECRET

      - name: built-nodejs
        build: dev-nodejs

#     - name: lint-nodejs
#       build: lint-nodejs

      - name: test-nodejs
        build: test-nodejs
