pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: lint-python
        build: lint-python
        run:
          env:
            DJANGO_SETTINGS_MODULE: "toolhub.settings"
            PIPELINE_RUNNING: 1

      - name: test-python
        build: test-python
        run:
          env:
            PIPELINE_RUNNING: 1
            DJANGO_SETTINGS_MODULE: "toolhub.settings"
            DJANGO_SECRET_KEY: NOTAREALSECRET
            DB_ENGINE: django.db.backends.sqlite3
            DB_NAME: ":memory:"
            WIKIMEDIA_OAUTH2_KEY: NOTAREALOAUTHKEY
            WIKIMEDIA_OAUTH2_SECRET: NOTAREALOAUTHSECRET

      - name: lint-nodejs
        build: lint-nodejs
        run:
          env:
            PIPELINE_RUNNING: 1

      - name: test-nodejs
        build: test-nodejs
        run:
          env:
            PIPELINE_RUNNING: 1
