pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: lint-python
        build: lint-python
        run:
          env: &python-env-settings
            PIPELINE_RUNNING: 1
            DJANGO_SECRET_KEY: NOTAREALSECRET
            WIKIMEDIA_OAUTH2_KEY: NOTAREALOAUTHKEY
            WIKIMEDIA_OAUTH2_SECRET: NOTAREALOAUTHSECRET

      - name: test-python
        build: test-python
        run:
          env: *python-env-settings

      - name: lint-nodejs
        build: lint-nodejs
        run:
          env: &node-env-settings
            PIPELINE_RUNNING: 1

      - name: test-nodejs
        build: test-nodejs
        run:
          env: *node-env-settings
